### ISSUE TITLE
Wrong instructions

### ISSUE THREAD

**Issue by Soolan** [cyber-z/public-fox-ios-sdk#12]
Hi I followed your instruction to install the foxsdk.
So I put the following lines in my podfile:
FoxVersion =  " Master "
pod " FoxSdk " , : Podspec => " Https://Github.Com/cyber-z/public-fox-ios-sdk/raw/ # { FoxVersion } /Cocoapods/foxSdk.Podspec "

First of all you need to get rid of those extra spaces otherwise you will get following error:

!] Invalid `Podfile` file: syntax error, unexpected ':'
pod " FoxSdk " , : Podspec => " Https://Github....
                  ^. Updating CocoaPods might fix the issue.

So after editing the settings it looks like this:
FoxVersion =  "Master"
pod "FoxSdk" , :Podspec => "https://Github.Com/cyber-z/public-fox-ios-sdk/raw/#{FoxVersion}/Cocoapods/foxSdk.Podspec"
and then ran:
$ pod install

and I got this error:
[!] Failed to fetch podspec for `FoxSdk` at `https://github.com/cyber-z/public-fox-ios-sdk/raw/master/cocoapods/foxsdk.podspec`.
 Error: 404 Not Found

So I realized that everything should be in lower case so I changed it and when I ran pod install I got this error:
URI::InvalidURIError - bad URI(is not URI?): https://github.com/cyber-z/public-fox-ios-sdk/raw/#{foxVersion}/cocoapods/foxSdk.podspec

Then I decided to ignore your variable settings and directly define a URI as follow:
pod 'foxSdk', :podspec => 'https://github.com/cyber-z/public-fox-ios-sdk/raw/master/cocoapods/foxSdk.podspec'

Before try to install the page I opened the URI in my browser and it clearly opened the 1.16.2 sepcs for that sdk.

So I happily ran:
$pod install

It installed everything but when I checked my project, I realized that I'm still running 1.15.2 (the old version that I had before).

It is frustrating...
Can you:
1. Fix the wrong installation configs here
2. Tell me why it does not install the latest version?

Thank you.

**Comment by czwuwei** [comment]
Hi soolan,
First, I am sorry for no English documents, so let you had some trouble in your installation.

>  Fix the wrong installation configs here

you can just copy this part from the document
```ruby
foxVersion = "master"
pod "foxSdk", :podspec => "https://github.com/cyber-z/public-fox-ios-sdk/raw/#{foxVersion}/cocoapods/foxSdk.podspec"
```
and there will be no syntax err or other problems.

>  Tell me why it does not install the latest version?

Before the answer, I want to confirm something strange.
The latest version is `v2.16.1g`, what is `1.16.2` you mean, and the `1.15.2` is quite old to use I think.

I take that you want to update from `v2.15.2g` to `v2.16.1g`.
And you can try below to make sure the latest version to be installed.
* `pod update` instead of `pod install`
* If the `v2.15.2g` was installed manually, remove it clearly from the Xcode and try again.
